### ISSUE TITLE
Mavenで取得しようとするとExcella-Core v2.0が存在しないため失敗する

### ISSUE THREAD

**Issue by mmakmo** [excella-core/excella-reports#15]
poi.xmlに記述されている、依存しているライブラリ Excella-Core のバージョンが1.9ではなく2.0となっているようですので、Mavenで取得できません。

**Comment by kamisono-bb** [comment]
masterの方は修正していますので、それに合わせて、pom.xmlのexcella-coreのバージョンを1.9に変更してください。次回リリース時には修正されます。

**Comment by kamisono-bb** [comment]
v1.8で修正しました。
