### ISSUE TITLE
POI3.16:行シフト先に結合セルが存在すると、結合が解除される

### ISSUE THREAD

**Issue by kamisono-bb** [excella-core/excella-reports#35]
https://bz.apache.org/bugzilla/show_bug.cgi?id=60384
https://bz.apache.org/bugzilla/show_bug.cgi?id=60709

原因のコミット：
https://github.com/apache/poi/commit/af2a99b910e714d495cfabb1378bea0401d48b0e

そのため、Excella側では、RowRepeatParamParser、RemoveAdapterの行シフト処理を０～最終列範囲の挿入、削除で対応する。

**Comment by maruTA-bis5** [comment]
38ba737 でこのissueに紐付くコミットがされていますが、他に修正を要する箇所はありますか?

**Comment by camy0113** [comment]
@maruTA-bis5 
この件についてはないはずです。issueのClose漏れだと思います。

**Comment by hibi-bb** [comment]
Close漏れということなのでCloseします。
