### ISSUE TITLE
ライセンスについて

### ISSUE THREAD

**Issue by flat1701** [excella-core/excella-reports#41]
ReadmeファイルにはLGPLライセンスと書かれていますが、LICENSEファイルはApacheライセンスと書かれています(View Licenseの表示がApacheLisenceとして表示されます)。

どちらが正しいのでしょうか？それともデュアルライセンスでしょうか？

**Comment by maruTA-bis5** [comment]
http://excella-core.github.io/ やそこからリンクされている各種メディア記事によると、LGPLが正しいようです。

**Comment by hibi-bb** [comment]
ライセンスはLGPLが正しいものとなります。
不要なファイルは削除します。

**Comment by hibi-bb** [comment]
マージしました。
